package org.bouncycastle.pqc.jcajce.provider;

import org.bouncycastle.asn1.bc.BCObjectIdentifiers;
import org.bouncycastle.jcajce.provider.config.ConfigurableProvider;
import org.bouncycastle.jcajce.provider.util.AsymmetricAlgorithmProvider;
import org.bouncycastle.jcajce.provider.util.AsymmetricKeyInfoConverter;
import org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi;

public class Snova {
  private static final String PREFIX = "org.bouncycastle.pqc.jcajce.provider.snova.";
  
  public static class Mappings extends AsymmetricAlgorithmProvider {
    public void configure(ConfigurableProvider param1ConfigurableProvider) {
      param1ConfigurableProvider.addAlgorithm("KeyFactory.Snova", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi");
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_4_SSK", BCObjectIdentifiers.snova_24_5_4_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_4_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_4_ESK", BCObjectIdentifiers.snova_24_5_4_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_4_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_4_SHAKE_SSK", BCObjectIdentifiers.snova_24_5_4_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_4_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_4_SHAKE_ESK", BCObjectIdentifiers.snova_24_5_4_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_4_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_5_SSK", BCObjectIdentifiers.snova_24_5_5_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_5_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_5_ESK", BCObjectIdentifiers.snova_24_5_5_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_5_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_5_SHAKE_SSK", BCObjectIdentifiers.snova_24_5_5_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_5_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_24_5_5_SHAKE_ESK", BCObjectIdentifiers.snova_24_5_5_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_24_5_5_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_25_8_3_SSK", BCObjectIdentifiers.snova_25_8_3_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_25_8_3_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_25_8_3_ESK", BCObjectIdentifiers.snova_25_8_3_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_25_8_3_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_25_8_3_SHAKE_SSK", BCObjectIdentifiers.snova_25_8_3_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_25_8_3_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_25_8_3_SHAKE_ESK", BCObjectIdentifiers.snova_25_8_3_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_25_8_3_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_29_6_5_SSK", BCObjectIdentifiers.snova_29_6_5_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_29_6_5_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_29_6_5_ESK", BCObjectIdentifiers.snova_29_6_5_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_29_6_5_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_29_6_5_SHAKE_SSK", BCObjectIdentifiers.snova_29_6_5_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_29_6_5_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_29_6_5_SHAKE_ESK", BCObjectIdentifiers.snova_29_6_5_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_29_6_5_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_8_4_SSK", BCObjectIdentifiers.snova_37_8_4_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_8_4_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_8_4_ESK", BCObjectIdentifiers.snova_37_8_4_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_8_4_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_8_4_SHAKE_SSK", BCObjectIdentifiers.snova_37_8_4_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_8_4_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_8_4_SHAKE_ESK", BCObjectIdentifiers.snova_37_8_4_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_8_4_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_17_2_SSK", BCObjectIdentifiers.snova_37_17_2_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_17_2_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_17_2_ESK", BCObjectIdentifiers.snova_37_17_2_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_17_2_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_17_2_SHAKE_SSK", BCObjectIdentifiers.snova_37_17_2_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_17_2_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_37_17_2_SHAKE_ESK", BCObjectIdentifiers.snova_37_17_2_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_37_17_2_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_49_11_3_SSK", BCObjectIdentifiers.snova_49_11_3_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_49_11_3_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_49_11_3_ESK", BCObjectIdentifiers.snova_49_11_3_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_49_11_3_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_49_11_3_SHAKE_SSK", BCObjectIdentifiers.snova_49_11_3_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_49_11_3_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_49_11_3_SHAKE_ESK", BCObjectIdentifiers.snova_49_11_3_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_49_11_3_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_56_25_2_SSK", BCObjectIdentifiers.snova_56_25_2_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_56_25_2_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_56_25_2_ESK", BCObjectIdentifiers.snova_56_25_2_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_56_25_2_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_56_25_2_SHAKE_SSK", BCObjectIdentifiers.snova_56_25_2_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_56_25_2_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_56_25_2_SHAKE_ESK", BCObjectIdentifiers.snova_56_25_2_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_56_25_2_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_60_10_4_SSK", BCObjectIdentifiers.snova_60_10_4_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_60_10_4_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_60_10_4_ESK", BCObjectIdentifiers.snova_60_10_4_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_60_10_4_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_60_10_4_SHAKE_SSK", BCObjectIdentifiers.snova_60_10_4_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_60_10_4_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_60_10_4_SHAKE_ESK", BCObjectIdentifiers.snova_60_10_4_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_60_10_4_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_66_15_3_SSK", BCObjectIdentifiers.snova_66_15_3_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_66_15_3_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_66_15_3_ESK", BCObjectIdentifiers.snova_66_15_3_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_66_15_3_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_66_15_3_SHAKE_SSK", BCObjectIdentifiers.snova_66_15_3_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_66_15_3_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_66_15_3_SHAKE_ESK", BCObjectIdentifiers.snova_66_15_3_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_66_15_3_SHAKE_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_75_33_2_SSK", BCObjectIdentifiers.snova_75_33_2_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_75_33_2_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_75_33_2_ESK", BCObjectIdentifiers.snova_75_33_2_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_75_33_2_ESK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_75_33_2_SHAKE_SSK", BCObjectIdentifiers.snova_75_33_2_shake_ssk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_75_33_2_SHAKE_SSK());
      addKeyFactoryAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyFactorySpi$SNOVA_75_33_2_SHAKE_ESK", BCObjectIdentifiers.snova_75_33_2_shake_esk, (AsymmetricKeyInfoConverter)new SnovaKeyFactorySpi.SNOVA_75_33_2_SHAKE_ESK());
      param1ConfigurableProvider.addAlgorithm("KeyPairGenerator.Snova", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi");
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_4_SSK", BCObjectIdentifiers.snova_24_5_4_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_4_ESK", BCObjectIdentifiers.snova_24_5_4_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_4_SHAKE_SSK", BCObjectIdentifiers.snova_24_5_4_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_4_SHAKE_ESK", BCObjectIdentifiers.snova_24_5_4_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_5_SSK", BCObjectIdentifiers.snova_24_5_5_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_5_ESK", BCObjectIdentifiers.snova_24_5_5_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_5_SHAKE_SSK", BCObjectIdentifiers.snova_24_5_5_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_24_5_5_SHAKE_ESK", BCObjectIdentifiers.snova_24_5_5_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_25_8_3_SSK", BCObjectIdentifiers.snova_25_8_3_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_25_8_3_ESK", BCObjectIdentifiers.snova_25_8_3_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_25_8_3_SHAKE_SSK", BCObjectIdentifiers.snova_25_8_3_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_25_8_3_SHAKE_ESK", BCObjectIdentifiers.snova_25_8_3_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_29_6_5_SSK", BCObjectIdentifiers.snova_29_6_5_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_29_6_5_ESK", BCObjectIdentifiers.snova_29_6_5_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_29_6_5_SHAKE_SSK", BCObjectIdentifiers.snova_29_6_5_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_29_6_5_SHAKE_ESK", BCObjectIdentifiers.snova_29_6_5_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_8_4_SSK", BCObjectIdentifiers.snova_37_8_4_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_8_4_ESK", BCObjectIdentifiers.snova_37_8_4_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_8_4_SHAKE_SSK", BCObjectIdentifiers.snova_37_8_4_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_8_4_SHAKE_ESK", BCObjectIdentifiers.snova_37_8_4_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_17_2_SSK", BCObjectIdentifiers.snova_37_17_2_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_17_2_ESK", BCObjectIdentifiers.snova_37_17_2_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_17_2_SHAKE_SSK", BCObjectIdentifiers.snova_37_17_2_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_37_17_2_SHAKE_ESK", BCObjectIdentifiers.snova_37_17_2_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_49_11_3_SSK", BCObjectIdentifiers.snova_49_11_3_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_49_11_3_ESK", BCObjectIdentifiers.snova_49_11_3_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_49_11_3_SHAKE_SSK", BCObjectIdentifiers.snova_49_11_3_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_49_11_3_SHAKE_ESK", BCObjectIdentifiers.snova_49_11_3_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_56_25_2_SSK", BCObjectIdentifiers.snova_56_25_2_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_56_25_2_ESK", BCObjectIdentifiers.snova_56_25_2_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_56_25_2_SHAKE_SSK", BCObjectIdentifiers.snova_56_25_2_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_56_25_2_SHAKE_ESK", BCObjectIdentifiers.snova_56_25_2_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_60_10_4_SSK", BCObjectIdentifiers.snova_60_10_4_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_60_10_4_ESK", BCObjectIdentifiers.snova_60_10_4_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_60_10_4_SHAKE_SSK", BCObjectIdentifiers.snova_60_10_4_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_60_10_4_SHAKE_ESK", BCObjectIdentifiers.snova_60_10_4_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_66_15_3_SSK", BCObjectIdentifiers.snova_66_15_3_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_66_15_3_ESK", BCObjectIdentifiers.snova_66_15_3_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_66_15_3_SHAKE_SSK", BCObjectIdentifiers.snova_66_15_3_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_66_15_3_SHAKE_ESK", BCObjectIdentifiers.snova_66_15_3_shake_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_75_33_2_SSK", BCObjectIdentifiers.snova_75_33_2_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_75_33_2_ESK", BCObjectIdentifiers.snova_75_33_2_esk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_75_33_2_SHAKE_SSK", BCObjectIdentifiers.snova_75_33_2_shake_ssk);
      addKeyPairGeneratorAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SnovaKeyPairGeneratorSpi$SNOVA_75_33_2_SHAKE_ESK", BCObjectIdentifiers.snova_75_33_2_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "Snova", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$Base", BCObjectIdentifiers.snova);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_4_SSK", BCObjectIdentifiers.snova_24_5_4_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_4_ESK", BCObjectIdentifiers.snova_24_5_4_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_4_SHAKE_SSK", BCObjectIdentifiers.snova_24_5_4_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_4_SHAKE_ESK", BCObjectIdentifiers.snova_24_5_4_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_5_SSK", BCObjectIdentifiers.snova_24_5_5_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_5_ESK", BCObjectIdentifiers.snova_24_5_5_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_5_SHAKE_SSK", BCObjectIdentifiers.snova_24_5_5_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_24_5_5_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_24_5_5_SHAKE_ESK", BCObjectIdentifiers.snova_24_5_5_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_25_8_3_SSK", BCObjectIdentifiers.snova_25_8_3_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_25_8_3_ESK", BCObjectIdentifiers.snova_25_8_3_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_25_8_3_SHAKE_SSK", BCObjectIdentifiers.snova_25_8_3_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_25_8_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_25_8_3_SHAKE_ESK", BCObjectIdentifiers.snova_25_8_3_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_29_6_5_SSK", BCObjectIdentifiers.snova_29_6_5_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_29_6_5_ESK", BCObjectIdentifiers.snova_29_6_5_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_29_6_5_SHAKE_SSK", BCObjectIdentifiers.snova_29_6_5_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_29_6_5_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_29_6_5_SHAKE_ESK", BCObjectIdentifiers.snova_29_6_5_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_8_4_SSK", BCObjectIdentifiers.snova_37_8_4_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_8_4_ESK", BCObjectIdentifiers.snova_37_8_4_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_8_4_SHAKE_SSK", BCObjectIdentifiers.snova_37_8_4_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_8_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_8_4_SHAKE_ESK", BCObjectIdentifiers.snova_37_8_4_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_17_2_SSK", BCObjectIdentifiers.snova_37_17_2_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_17_2_ESK", BCObjectIdentifiers.snova_37_17_2_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_17_2_SHAKE_SSK", BCObjectIdentifiers.snova_37_17_2_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_37_17_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_37_17_2_SHAKE_ESK", BCObjectIdentifiers.snova_37_17_2_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_49_11_3_SSK", BCObjectIdentifiers.snova_49_11_3_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_49_11_3_ESK", BCObjectIdentifiers.snova_49_11_3_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_49_11_3_SHAKE_SSK", BCObjectIdentifiers.snova_49_11_3_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_49_11_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_49_11_3_SHAKE_ESK", BCObjectIdentifiers.snova_49_11_3_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_56_25_2_SSK", BCObjectIdentifiers.snova_56_25_2_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_56_25_2_ESK", BCObjectIdentifiers.snova_56_25_2_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_56_25_2_SHAKE_SSK", BCObjectIdentifiers.snova_56_25_2_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_56_25_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_56_25_2_SHAKE_ESK", BCObjectIdentifiers.snova_56_25_2_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_60_10_4_SSK", BCObjectIdentifiers.snova_60_10_4_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_60_10_4_ESK", BCObjectIdentifiers.snova_60_10_4_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_60_10_4_SHAKE_SSK", BCObjectIdentifiers.snova_60_10_4_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_60_10_4_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_60_10_4_SHAKE_ESK", BCObjectIdentifiers.snova_60_10_4_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_66_15_3_SSK", BCObjectIdentifiers.snova_66_15_3_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_66_15_3_ESK", BCObjectIdentifiers.snova_66_15_3_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_66_15_3_SHAKE_SSK", BCObjectIdentifiers.snova_66_15_3_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_66_15_3_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_66_15_3_SHAKE_ESK", BCObjectIdentifiers.snova_66_15_3_shake_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_75_33_2_SSK", BCObjectIdentifiers.snova_75_33_2_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_75_33_2_ESK", BCObjectIdentifiers.snova_75_33_2_esk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SHAKE_SSK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_75_33_2_SHAKE_SSK", BCObjectIdentifiers.snova_75_33_2_shake_ssk);
      addSignatureAlgorithm(param1ConfigurableProvider, "SNOVA_75_33_2_SHAKE_ESK", "org.bouncycastle.pqc.jcajce.provider.snova.SignatureSpi$SNOVA_75_33_2_SHAKE_ESK", BCObjectIdentifiers.snova_75_33_2_shake_esk);
    }
  }
}


/* Location:              C:\Users\ranor\AppData\Roaming\Hytale\install\release\package\game\latest\Server\HytaleServer.jar!\org\bouncycastle\pqc\jcajce\provider\Snova.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */