/*      */ package com.hypixel.hytale.server.core;
/*      */ 
/*      */ import com.hypixel.hytale.codec.Codec;
/*      */ import com.hypixel.hytale.codec.KeyedCodec;
/*      */ import com.hypixel.hytale.codec.builder.BuilderCodec;
/*      */ import java.time.Duration;
/*      */ import java.util.function.Supplier;
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ public class TimeoutProfile
/*      */ {
/*  949 */   private static final TimeoutProfile SINGLEPLAYER_DEFAULTS = new TimeoutProfile(
/*  950 */       Duration.ofSeconds(30L), 
/*  951 */       Duration.ofSeconds(60L), Duration.ofSeconds(60L), Duration.ofSeconds(60L), Duration.ofSeconds(30L), 
/*  952 */       Duration.ofSeconds(60L), Duration.ofSeconds(120L), 
/*  953 */       Duration.ofSeconds(30L), Duration.ofSeconds(300L), Duration.ofSeconds(300L), Duration.ofSeconds(120L));
/*      */ 
/*      */ 
/*      */   
/*  957 */   private static final TimeoutProfile MULTIPLAYER_DEFAULTS = new TimeoutProfile(
/*  958 */       Duration.ofSeconds(15L), 
/*  959 */       Duration.ofSeconds(30L), Duration.ofSeconds(30L), Duration.ofSeconds(30L), Duration.ofSeconds(15L), 
/*  960 */       Duration.ofSeconds(45L), Duration.ofSeconds(60L), 
/*  961 */       Duration.ofSeconds(15L), Duration.ofSeconds(120L), Duration.ofSeconds(120L), Duration.ofSeconds(60L)); public static final Codec<TimeoutProfile> CODEC; private Duration initial;
/*      */   private Duration auth;
/*      */   
/*      */   public static TimeoutProfile defaults() {
/*  965 */     return Constants.SINGLEPLAYER ? SINGLEPLAYER_DEFAULTS : MULTIPLAYER_DEFAULTS;
/*      */   }
/*      */   
/*      */   private Duration authGrant;
/*      */   private Duration authToken;
/*      */   private Duration authServerExchange;
/*      */   private Duration password;
/*      */   private Duration play;
/*      */   private Duration setupWorldSettings;
/*      */   private Duration setupAssetsRequest;
/*      */   private Duration setupSendAssets;
/*      */   private Duration setupAddToUniverse;
/*      */   private transient HytaleServerConfig hytaleServerConfig;
/*      */   
/*      */   static {
/*  980 */     CODEC = (Codec<TimeoutProfile>)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)((BuilderCodec.Builder)BuilderCodec.builder(TimeoutProfile.class, TimeoutProfile::new).addField(new KeyedCodec("InitialTimeout", (Codec)Codec.DURATION), (o, d) -> o.initial = d, o -> o.initial)).addField(new KeyedCodec("AuthTimeout", (Codec)Codec.DURATION), (o, d) -> o.auth = d, o -> o.auth)).addField(new KeyedCodec("AuthGrantTimeout", (Codec)Codec.DURATION), (o, d) -> o.authGrant = d, o -> o.authGrant)).addField(new KeyedCodec("AuthTokenTimeout", (Codec)Codec.DURATION), (o, d) -> o.authToken = d, o -> o.authToken)).addField(new KeyedCodec("AuthServerExchangeTimeout", (Codec)Codec.DURATION), (o, d) -> o.authServerExchange = d, o -> o.authServerExchange)).addField(new KeyedCodec("PasswordTimeout", (Codec)Codec.DURATION), (o, d) -> o.password = d, o -> o.password)).addField(new KeyedCodec("PlayTimeout", (Codec)Codec.DURATION), (o, d) -> o.play = d, o -> o.play)).addField(new KeyedCodec("SetupWorldSettings", (Codec)Codec.DURATION), (o, d) -> o.setupWorldSettings = d, o -> o.setupWorldSettings)).addField(new KeyedCodec("SetupAssetsRequest", (Codec)Codec.DURATION), (o, d) -> o.setupAssetsRequest = d, o -> o.setupAssetsRequest)).addField(new KeyedCodec("SetupSendAssets", (Codec)Codec.DURATION), (o, d) -> o.setupSendAssets = d, o -> o.setupSendAssets)).addField(new KeyedCodec("SetupAddToUniverse", (Codec)Codec.DURATION), (o, d) -> o.setupAddToUniverse = d, o -> o.setupAddToUniverse)).build();
/*      */   }
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */   
/*      */   public TimeoutProfile() {}
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */   
/*      */   public TimeoutProfile(HytaleServerConfig hytaleServerConfig) {
/* 1000 */     this.hytaleServerConfig = hytaleServerConfig;
/*      */   }
/*      */ 
/*      */ 
/*      */ 
/*      */   
/*      */   private TimeoutProfile(Duration initial, Duration auth, Duration authGrant, Duration authToken, Duration authServerExchange, Duration password, Duration play, Duration worldSettings, Duration assetsRequest, Duration sendAssets, Duration addToUniverse) {
/* 1007 */     this.initial = initial;
/* 1008 */     this.auth = auth;
/* 1009 */     this.authGrant = authGrant;
/* 1010 */     this.authToken = authToken;
/* 1011 */     this.authServerExchange = authServerExchange;
/* 1012 */     this.password = password;
/* 1013 */     this.play = play;
/* 1014 */     this.setupWorldSettings = worldSettings;
/* 1015 */     this.setupAssetsRequest = assetsRequest;
/* 1016 */     this.setupSendAssets = sendAssets;
/* 1017 */     this.setupAddToUniverse = addToUniverse;
/*      */   }
/*      */   
/*      */   public Duration getInitial() {
/* 1021 */     return (this.initial != null) ? this.initial : (defaults()).initial; } public void setInitial(Duration d) {
/* 1022 */     this.initial = d; markChanged();
/*      */   }
/*      */   
/* 1025 */   public Duration getAuth() { return (this.auth != null) ? this.auth : (defaults()).auth; } public void setAuth(Duration d) {
/* 1026 */     this.auth = d; markChanged();
/*      */   }
/*      */   
/* 1029 */   public Duration getAuthGrant() { return (this.authGrant != null) ? this.authGrant : (defaults()).authGrant; } public void setAuthGrant(Duration d) {
/* 1030 */     this.authGrant = d; markChanged();
/*      */   }
/*      */   
/* 1033 */   public Duration getAuthToken() { return (this.authToken != null) ? this.authToken : (defaults()).authToken; } public void setAuthToken(Duration d) {
/* 1034 */     this.authToken = d; markChanged();
/*      */   }
/*      */   
/* 1037 */   public Duration getAuthServerExchange() { return (this.authServerExchange != null) ? this.authServerExchange : (defaults()).authServerExchange; } public void setAuthServerExchange(Duration d) {
/* 1038 */     this.authServerExchange = d; markChanged();
/*      */   }
/*      */   
/* 1041 */   public Duration getPassword() { return (this.password != null) ? this.password : (defaults()).password; } public void setPassword(Duration d) {
/* 1042 */     this.password = d; markChanged();
/*      */   }
/*      */   
/* 1045 */   public Duration getPlay() { return (this.play != null) ? this.play : (defaults()).play; } public void setPlay(Duration d) {
/* 1046 */     this.play = d; markChanged();
/*      */   }
/*      */   
/* 1049 */   public Duration getSetupWorldSettings() { return (this.setupWorldSettings != null) ? this.setupWorldSettings : (defaults()).setupWorldSettings; } public void setSetupWorldSettings(Duration d) {
/* 1050 */     this.setupWorldSettings = d; markChanged();
/*      */   }
/*      */   
/* 1053 */   public Duration getSetupAssetsRequest() { return (this.setupAssetsRequest != null) ? this.setupAssetsRequest : (defaults()).setupAssetsRequest; } public void setSetupAssetsRequest(Duration d) {
/* 1054 */     this.setupAssetsRequest = d; markChanged();
/*      */   }
/*      */   
/* 1057 */   public Duration getSetupSendAssets() { return (this.setupSendAssets != null) ? this.setupSendAssets : (defaults()).setupSendAssets; } public void setSetupSendAssets(Duration d) {
/* 1058 */     this.setupSendAssets = d; markChanged();
/*      */   }
/*      */   
/* 1061 */   public Duration getSetupAddToUniverse() { return (this.setupAddToUniverse != null) ? this.setupAddToUniverse : (defaults()).setupAddToUniverse; } public void setSetupAddToUniverse(Duration d) {
/* 1062 */     this.setupAddToUniverse = d; markChanged();
/*      */   } private void markChanged() {
/* 1064 */     if (this.hytaleServerConfig != null) this.hytaleServerConfig.markChanged(); 
/*      */   }
/*      */   void setHytaleServerConfig(HytaleServerConfig hytaleServerConfig) {
/* 1067 */     this.hytaleServerConfig = hytaleServerConfig;
/*      */   }
/*      */ }


/* Location:              C:\Users\ranor\AppData\Roaming\Hytale\install\release\package\game\latest\Server\HytaleServer.jar!\com\hypixel\hytale\server\core\HytaleServerConfig$TimeoutProfile.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.1.3
 */